name: Build Lambda Package

on: push

jobs:
  build-lambda-package:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      AWS_DEFAULT_REGION: eu-central-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Package Lambda and Requirements
        run: |
          pip install -r src/requirements.txt -t src
          mkdir build
          zip -9 -r build/pkg-lambda.zip src
          pip install awscli
          aws s3 sync --delete ./build s3://annomate-lambdas/test/

