name: Build Lambda Package

on: push

jobs:
  build-lambda-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Package Lambda and Requirements
        run: |
          pip install -r src/requirements.txt -t src
          mkdir build
          zip -9 -r build/pkg-lambda.zip src
          pip install awscli
          aws s3 sync --delete ./build s3://annomate-lambdas/test/

