name: Build
on: push
jobs:
  plan-dev:
    runs-on: ubuntu-latest
    steps:
      run: echo "not implemented yet!"
  
  apply-dev:
    runs-on: ubuntu-latest
    steps:
      run: echo "not implemented yet!"