name: Terraform Deployment

on: 
  workflow_run:
    workflows: ["build-lambda-package"]
    types:
      - "completed"




jobs:
  plan-development:
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      AWS_DEFAULT_REGION: eu-central-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        id: init
        run: |
          cd deploy
          terraform init
      - name: Terraform Plan
        id: plan
        run: |
          cd deploy
          terraform plan \
          -var 'build_tag=${{ github.sha }}' \
          -var 'project_name=${{ github.event.repository.name }}'
      - name: Terraform Apply
        id: apply
        run: |
          cd deploy
          terraform apply -auto-approve \
          -var 'build_tag=${{ github.sha }}' \
          -var 'project_name=${{ github.event.repository.name }}'