name: Terraform

on:
  workflow_call:
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true

jobs:
  deploy_terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        id: init
        run: |
          cd deploy
          terraform init
      - name: Terraform Plan
        id: plan
        run: |
          cd deploy
          terraform plan \
          -var 'build_tag=${{ github.sha }}' \
          -var 'project_name=some_name'