name: Deploy Terraform
on: push
jobs:
  plan-dev:
    runs-on: ubuntu-latest
    # interruptible: false
    
    steps:
      - run: |
          echo "not implemented yet!"
          ls

  
  apply-dev:
    runs-on: ubuntu-latest
    steps:
      - run: echo "not implemented yet!"