name: Terraform Deployment

on: push

jobs:
  plan-development:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-central-1"
      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        id: init
        run: |
          cd deploy
          terraform init
      - name: Terraform Plan
        id: plan
        run: |
          cd deploy
          terraform plan -input=false

  
  apply-dev:
    runs-on: ubuntu-latest
    steps:
      - run: echo "not implemented yet!"